### ISSUE TITLE
Thoughts On Adding More Music

### ISSUE THREAD

**Issue by Quinncuatro** [klitscher/adj#8]
Hey team! This is cool as hell.

Had some thoughts on extending this out to other playlists without having to make that static song-mapping file.

I'd check out [Festify](https://github.com/Festify/app) as a way to piggy back on something like Spotify.

Once you have that, I'd look into using something like the Music Genome Project (a Pandora project) or Gracenote to be able to get keywords that aim to pinpoint the essence of a song.

So you can load up a playlist you built in Spotify, cross reference it against Gracenote, and then use that in ADJ.

Just my $0.02.

**Comment by roryfahy** [comment]
hey this looks like a ton of good advice, we're going to look into it!
