### ISSUE TITLE
Put the ADJ landing page on your repo.

### ISSUE THREAD

**Issue by Quinncuatro** [klitscher/adj#9]
Pretty much the title. Put the link to your landing page in the site field at the top of your repo. :P

**Comment by roryfahy** [comment]
hey because its a wixsite, we werent able to redirect through github pages but we did link to it at the top of our readme.  cheers

**Comment by Quinncuatro** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/5264878/68055698-a6e18600-fcc7-11e9-9c96-4d92925d7f85.png">
This spot ^^
